In [6]:
import pandas as pd
import numpy as np
import pymongo
import psycopg2
import streamlit as st
from pymongo import MongoClient
import plotly.express as px
from streamlit_option_menu import option_menu
pd.set_option('display.max_columns', None)
import urllib.parse
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
username = "Bhavani_Bairi"
password = "Havish@123$"
#Escaped username and Escaped password
escaped_username = urllib.parse.quote_plus(username)
escaped_password = urllib.parse.quote_plus(password)

connect_string = f'mongodb+srv://{escaped_username}:{escaped_password}@airbnb.d117ty2.mongodb.net/?retryWrites=true&w=majority&appName=Airbnb'

client = pymongo.MongoClient(connect_string)

In [11]:
db = client.sample_airbnb

In [12]:
col = db.listingsAndReviews

In [14]:
data = []
for i in col.find():
    data1 = dict(Id = i['_id'],
                Listing_url = i['listing_url'],
                Name = i.get('name'),
                Description = i['description'],
                Property_type = i['property_type'],
                Room_type = i['room_type'],
                Bed_type = i['bed_type'],
                Min_nights = int(i['minimum_nights']),
                Max_nights = int(i['maximum_nights']),
                Cancellation_policy = i['cancellation_policy'],
                Accomodates = i['accommodates'],
                Total_bedrooms = i.get('bedrooms'),
                Total_beds = i.get('beds'),
                No_of_reviews = i['number_of_reviews'],
                Price = i['price'],
                Security_deposit = i.get('security_deposit'),
                Cleaning_fee = i.get('cleaning_fee'),
                Extra_people = i['extra_people'],
                Guests_included= i['guests_included'],
                Amenities = ', '.join(i['amenities']),
                Host_id = i['host']['host_id'],
                Host_name = i['host']['host_name'],
                Host_neighbourhood = i['host']['host_neighbourhood'],
                Street = i['address']['street'],
                Country = i['address']['country'],
                Country_code = i['address']['country_code'],
                Availability_30 = i['availability']['availability_30'],
                Availability_60 = i['availability']['availability_60'],
                Availability_90 = i['availability']['availability_90'],
                Availability_365 = i['availability']['availability_365'],
                Review_scores = i['review_scores'].get('review_scores_rating'),
                Location_type = i['address']['location']['type'],
                Longitude = i['address']['location']['coordinates'][0],
                Latitude = i['address']['location']['coordinates'][1],
                Is_location_exact = i['address']['location']['is_location_exact']
                )
    data.append(data1)

In [22]:
df = pd.DataFrame(data)

In [23]:
df

,Id,Listing_url,Name,Description,Property_type,Room_type,Bed_type,Min_nights,Max_nights,Cancellation_policy,Accomodates,Total_bedrooms,Total_beds,No_of_reviews,Price,Security_deposit,Cleaning_fee,Extra_people,Guests_included,Amenities,Host_id,Host_name,Host_neighbourhood,Street,Country,Country_code,Availability_30,Availability_60,Availability_90,Availability_365,Review_scores,Location_type,Longitude,Latitude,Is_location_exact
0,10051164,https://www.airbnb.com/rooms/10051164,Catete's Colonial Big Hause Room B,"Old floor, intirely reformed, destined to rece...",House,Private room,Real Bed,2,1125,strict_14_with_grace_period,8,1.0,8.0,1,250.00,0.00,0.00,40.00,4,"TV, Cable TV, Internet, Wifi, Air conditioning...",51326285,Beatriz,Catete,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,10,10,21,296,80.0,Point,-43.180157,-22.926382,True
1,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Quarto com vista para a Lagoa Rodrigo de Freit...,Apartment,Private room,Real Bed,1,1125,flexible,2,1.0,1.0,0,701.00,1000.00,250.00,0.00,1,"TV, Cable TV, Internet, Wifi, Air conditioning...",51496939,Livia,Lagoa,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,28,58,88,363,NaN,Point,-43.205047,-22.971951,True
2,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,"Murphy bed, optional second bedroom available....",Apartment,Private room,Real Bed,12,360,strict_14_with_grace_period,2,1.0,1.0,70,135.00,0.00,135.00,0.00,1,"Internet, Wifi, Air conditioning, Kitchen, Ele...",454250,Greta,,"New York, NY, United States",United States,US,0,0,0,93,94.0,Point,-73.965230,40.799620,False
3,10009999,https://www.airbnb.com/rooms/10009999,Horto flat with small garden,One bedroom + sofa-bed in quiet and bucolic ne...,Apartment,Entire home/apt,Real Bed,2,1125,flexible,4,1.0,2.0,0,317.00,None,187.00,0.00,1,"Wifi, Wheelchair accessible, Kitchen, Free par...",1282196,Ynaie,Jardim Botânico,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,0,0,0,0,NaN,Point,-43.230750,-22.966254,True
4,10069642,https://www.airbnb.com/rooms/10069642,Ótimo Apto proximo Parque Olimpico,Apartamento próximo ao centro dos Jogos Olímpi...,Apartment,Entire home/apt,Real Bed,15,20,strict_14_with_grace_period,5,2.0,2.0,0,858.00,4476.00,112.00,75.00,1,"TV, Cable TV, Internet, Wifi, Air conditioning...",51670240,Jonathan,,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,0,0,0,0,NaN,Point,-43.431112,-23.000358,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9577071,https://www.airbnb.com/rooms/9577071,Beachside apt in North Bondi,Perfect place for a couple and / or with two k...,Apartment,Entire home/apt,Real Bed,5,1125,moderate,2,2.0,3.0,4,151.00,None,150.00,0.00,1,"TV, Cable TV, Wifi, Kitchen, Heating, Family/k...",528140,Jason,North Bondi,"North Bondi, NSW, Australia",Australia,AU,0,0,0,0,100.0,Point,151.284250,-33.892860,True
5551,9774127,https://www.airbnb.com/rooms/9774127,Valor promocional para Carnaval 2019,Apto com uma linda vista para o mar c/ 2 pisc...,Apartment,Entire home/apt,Real Bed,4,90,strict_14_with_grace_period,4,2.0,4.0,0,351.00,2000.00,130.00,0.00,1,"TV, Cable TV, Wifi, Air conditioning, Wheelcha...",1221463,Alex,,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,23,53,83,358,NaN,Point,-43.431552,-23.009790,False
5552,9936016,https://www.airbnb.com/rooms/9936016,Alugo Apartamento na Tijuca,Apartamento amplo que acomoda 6 pessoas. Um qu...,Apartment,Entire home/apt,Real Bed,1,1125,flexible,6,1.0,2.0,0,750.00,None,None,0.00,1,"TV, Cable TV, Internet, Wifi, Air conditioning...",47092481,Aliane,,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,0,0,0,0,NaN,Point,-43.173761,-22.908336,False
5553,9979991,https://www.airbnb.com/rooms/9979991,,"Located at the heart of Kowloon, our unit is s...",Apartment,Entire home/apt,Real Bed,1,1125,flexible,3,1.0,1.0,0,1052.00,None,None,0.00,1,"TV, Internet, Air conditioning, Kitchen, Eleva...",51283546,Alexis,,"Hong Kong, Kowloon, Hong Kong",Hong Kong,HK,0,0,0,0,NaN,Point,114.169630,22.315690,False
5554,9944044,https://www.airbnb.com/rooms/9944044,Sanctuary Bundeena,"Relax and revitalise in our spacious, self-con...",Bed and breakfast,Private room,Real Bed,2,1125,moderate,2,1.0,1.0,1,250.00,None,None,0.00,1,"TV, Internet, Wifi, Kitchen, Free parking on p...",51104303,Sara And Scott,,"Bundeena, NSW, Australia",Australia,AU,30,60,90,365,100.0,Point,151.152710,-34.088290,True

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5555 entries, 0 to 5554
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   5555 non-null   object
 1   Listing_url          5555 non-null   object
 2   Name                 5555 non-null   object
 3   Description          5555 non-null   object
 4   Property_type        5555 non-null   object
 5   Room_type            5555 non-null   object
 6   Bed_type             5555 non-null   object
 7   Min_nights           5555 non-null   int64
 8   Max_nights           5555 non-null   int64
 9   Cancellation_policy  5555 non-null   object
 10  Accomodates          5555 non-null   int64
 11  Total_bedrooms       5550 non-null   float64
 12  Total_beds           5542 non-null   float64
 13  No_of_reviews        5555 non-null   int64
 14  Price                5555 non-null   object
 15  Security_deposit     3471 non-null   object
 16  Cleaning_fee         4024 non-null   object
 17  Extra_people         5555 non-null   object
 18  Guests_included      5555 non-null   object
 19  Amenities            5555 non-null   object
 20  Host_id              5555 non-null   object
 21  Host_name            5555 non-null   object
 22  Host_neighbourhood   5555 non-null   object
 23  Street               5555 non-null   object
 24  Country              5555 non-null   object
 25  Country_code         5555 non-null   object
 26  Availability_30      5555 non-null   int64
 27  Availability_60      5555 non-null   int64
 28  Availability_90      5555 non-null   int64
 29  Availability_365     5555 non-null   int64
 30  Review_scores        4081 non-null   float64
 31  Location_type        5555 non-null   object
 32  Longitude            5555 non-null   float64
 33  Latitude             5555 non-null   float64
 34  Is_location_exact    5555 non-null   bool
dtypes: bool(1), float64(5), int64(8), object(21)
memory usage: 1.4+ MB

In [25]:
from bson import Decimal128
from decimal import Decimal

df.Security_deposit = df.Security_deposit[~df.Security_deposit.isna()].astype(str).astype(float)
df.Cleaning_fee = df.Cleaning_fee[~df.Cleaning_fee.isna()].astype(str).astype(float)
df["Price"] = df['Price'].apply(lambda x: float(x.to_decimal()) if isinstance(x, Decimal128) else float(x))
df["Extra_people"] = df["Extra_people"].apply(lambda x: float(x.to_decimal()) if isinstance(x, Decimal128) else float(x))
df["Guests_included"] = df['Guests_included'].apply(lambda x: float(x.to_decimal()) if isinstance(x, Decimal128) else float(x))
df["Id"] = df["Id"].astype("Int64")

In [26]:
df.isna().sum()

Id                        0
Listing_url               0
Name                      0
Description               0
Property_type             0
Room_type                 0
Bed_type                  0
Min_nights                0
Max_nights                0
Cancellation_policy       0
Accomodates               0
Total_bedrooms            5
Total_beds               13
No_of_reviews             0
Price                     0
Security_deposit       2084
Cleaning_fee           1531
Extra_people              0
Guests_included           0
Amenities                 0
Host_id                   0
Host_name                 0
Host_neighbourhood        0
Street                    0
Country                   0
Country_code              0
Availability_30           0
Availability_60           0
Availability_90           0
Availability_365          0
Review_scores          1474
Location_type             0
Longitude                 0
Latitude                  0
Is_location_exact         0
dtype: int64

In [27]:
df["Total_bedrooms"].fillna(df["Total_bedrooms"].mode()[0], inplace=True)
df["Total_beds"].fillna(df["Total_beds"].mode()[0], inplace=True)
df["Security_deposit"].fillna(df["Security_deposit"].median(),inplace=True)
df["Cleaning_fee"].fillna(df["Cleaning_fee"].median(), inplace=True)
df["Review_scores"].fillna(df["Review_scores"].median(),inplace=True)

C:\Users\rajub\AppData\Local\Temp\ipykernel_11920\588719992.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Total_bedrooms"].fillna(df["Total_bedrooms"].mode()[0], inplace=True)
C:\Users\rajub\AppData\Local\Temp\ipykernel_11920\588719992.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Total_beds"].fillna(df["Total_beds"].mode()[0], inplace=True)
C:\Users\rajub\AppData\Local\Temp\ipykernel_11920\588719992.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Security_deposit"].fillna(df["Security_deposit"].median(),inplace=True)
C:\Users\rajub\AppData\Local\Temp\ipykernel_11920\588719992.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Cleaning_fee"].fillna(df["Cleaning_fee"].median(), inplace=True)
C:\Users\rajub\AppData\Local\Temp\ipykernel_11920\588719992.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Review_scores"].fillna(df["Review_scores"].median(),inplace=True)

In [28]:
# Filling Empty values in Description and House rules columns
df.Description.replace(to_replace='',value='No description provided',inplace=True)
df.Amenities.replace(to_replace='',value='Information not available',inplace=True)
df.Host_neighbourhood.replace(to_replace='',value='Not mentioned', inplace=True)

C:\Users\rajub\AppData\Local\Temp\ipykernel_11920\2308539249.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Description.replace(to_replace='',value='No description provided',inplace=True)
C:\Users\rajub\AppData\Local\Temp\ipykernel_11920\2308539249.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Amenities.replace(to_replace='',value='Information not available',inplace=True)

In [29]:
df.isna().sum()

Id                     0
Listing_url            0
Name                   0
Description            0
Property_type          0
Room_type              0
Bed_type               0
Min_nights             0
Max_nights             0
Cancellation_policy    0
Accomodates            0
Total_bedrooms         0
Total_beds             0
No_of_reviews          0
Price                  0
Security_deposit       0
Cleaning_fee           0
Extra_people           0
Guests_included        0
Amenities              0
Host_id                0
Host_name              0
Host_neighbourhood     0
Street                 0
Country                0
Country_code           0
Availability_30        0
Availability_60        0
Availability_90        0
Availability_365       0
Review_scores          0
Location_type          0
Longitude              0
Latitude               0
Is_location_exact      0
dtype: int64

In [30]:

df.duplicated().sum()

0

In [31]:
# Name Column has empty values and some duplicates hence dropping them
df.drop(labels=list(df[df.Name.duplicated(keep=False)].index),inplace=True)

In [32]:
df.reset_index(drop=True,inplace=True)

In [34]:
# Converting dataframe to csv file and saving it
df.to_csv('Airbnb_data.csv',index=False)